// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module copy_local_beta (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        beta_buffer_address0,
        beta_buffer_ce0,
        beta_buffer_q0,
        local_beta_buffer_0,
        local_beta_buffer_1,
        local_beta_buffer_2,
        local_beta_buffer_3,
        local_beta_buffer_4,
        local_beta_buffer_5,
        local_beta_buffer_6,
        local_beta_buffer_7,
        local_beta_buffer_8,
        local_beta_buffer_9,
        local_beta_buffer_10,
        local_beta_buffer_11,
        local_beta_buffer_12,
        local_beta_buffer_13,
        local_beta_buffer_14,
        local_beta_buffer_15,
        local_beta_buffer_16,
        local_beta_buffer_17,
        local_beta_buffer_18,
        local_beta_buffer_19,
        local_beta_buffer_20,
        local_beta_buffer_21,
        local_beta_buffer_22,
        local_beta_buffer_23,
        local_beta_buffer_24,
        local_beta_buffer_25,
        local_beta_buffer_26,
        local_beta_buffer_27,
        local_beta_buffer_28,
        local_beta_buffer_29,
        local_beta_buffer_30,
        local_beta_buffer_31,
        m,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9,
        ap_return_10,
        ap_return_11,
        ap_return_12,
        ap_return_13,
        ap_return_14,
        ap_return_15,
        ap_return_16,
        ap_return_17,
        ap_return_18,
        ap_return_19,
        ap_return_20,
        ap_return_21,
        ap_return_22,
        ap_return_23,
        ap_return_24,
        ap_return_25,
        ap_return_26,
        ap_return_27,
        ap_return_28,
        ap_return_29,
        ap_return_30,
        ap_return_31
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_pp0_stage0 = 3'd2;
parameter    ap_ST_fsm_state4 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [9:0] beta_buffer_address0;
output   beta_buffer_ce0;
input  [31:0] beta_buffer_q0;
input  [7:0] local_beta_buffer_0;
input  [7:0] local_beta_buffer_1;
input  [7:0] local_beta_buffer_2;
input  [7:0] local_beta_buffer_3;
input  [7:0] local_beta_buffer_4;
input  [7:0] local_beta_buffer_5;
input  [7:0] local_beta_buffer_6;
input  [7:0] local_beta_buffer_7;
input  [7:0] local_beta_buffer_8;
input  [7:0] local_beta_buffer_9;
input  [7:0] local_beta_buffer_10;
input  [7:0] local_beta_buffer_11;
input  [7:0] local_beta_buffer_12;
input  [7:0] local_beta_buffer_13;
input  [7:0] local_beta_buffer_14;
input  [7:0] local_beta_buffer_15;
input  [7:0] local_beta_buffer_16;
input  [7:0] local_beta_buffer_17;
input  [7:0] local_beta_buffer_18;
input  [7:0] local_beta_buffer_19;
input  [7:0] local_beta_buffer_20;
input  [7:0] local_beta_buffer_21;
input  [7:0] local_beta_buffer_22;
input  [7:0] local_beta_buffer_23;
input  [7:0] local_beta_buffer_24;
input  [7:0] local_beta_buffer_25;
input  [7:0] local_beta_buffer_26;
input  [7:0] local_beta_buffer_27;
input  [7:0] local_beta_buffer_28;
input  [7:0] local_beta_buffer_29;
input  [7:0] local_beta_buffer_30;
input  [7:0] local_beta_buffer_31;
input  [31:0] m;
output  [7:0] ap_return_0;
output  [7:0] ap_return_1;
output  [7:0] ap_return_2;
output  [7:0] ap_return_3;
output  [7:0] ap_return_4;
output  [7:0] ap_return_5;
output  [7:0] ap_return_6;
output  [7:0] ap_return_7;
output  [7:0] ap_return_8;
output  [7:0] ap_return_9;
output  [7:0] ap_return_10;
output  [7:0] ap_return_11;
output  [7:0] ap_return_12;
output  [7:0] ap_return_13;
output  [7:0] ap_return_14;
output  [7:0] ap_return_15;
output  [7:0] ap_return_16;
output  [7:0] ap_return_17;
output  [7:0] ap_return_18;
output  [7:0] ap_return_19;
output  [7:0] ap_return_20;
output  [7:0] ap_return_21;
output  [7:0] ap_return_22;
output  [7:0] ap_return_23;
output  [7:0] ap_return_24;
output  [7:0] ap_return_25;
output  [7:0] ap_return_26;
output  [7:0] ap_return_27;
output  [7:0] ap_return_28;
output  [7:0] ap_return_29;
output  [7:0] ap_return_30;
output  [7:0] ap_return_31;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg beta_buffer_ce0;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg  signed [31:0] offset_reg_635;
reg   [5:0] tm_reg_644;
wire   [31:0] tmp_fu_655_p2;
reg   [31:0] tmp_reg_2360;
wire   [0:0] exitcond_fu_821_p2;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_state2_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_11001;
wire   [5:0] tm_3_fu_826_p2;
reg    ap_enable_reg_pp0_iter0;
wire   [4:0] tmp_204_fu_837_p1;
reg   [4:0] tmp_204_reg_2379;
wire   [31:0] offset_1_fu_841_p2;
wire    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state2;
reg    ap_enable_reg_pp0_iter1;
wire  signed [63:0] tmp_s_fu_832_p1;
wire    ap_block_pp0_stage0;
reg   [7:0] local_beta_buffer_V_32_fu_168;
wire   [7:0] tmp_203_fu_847_p1;
wire    ap_CS_fsm_state4;
reg   [0:0] write_flag_fu_172;
reg   [0:0] write_flag31_fu_176;
reg   [7:0] local_beta_buffer_V_31_fu_180;
reg   [7:0] local_beta_buffer_V_30_fu_184;
reg   [0:0] write_flag30_fu_188;
reg   [7:0] local_beta_buffer_V_29_fu_192;
reg   [0:0] write_flag4_fu_196;
reg   [0:0] write_flag29_fu_200;
reg   [7:0] local_beta_buffer_V_28_fu_204;
reg   [7:0] local_beta_buffer_V_27_fu_208;
reg   [0:0] write_flag28_fu_212;
reg   [7:0] local_beta_buffer_V_26_fu_216;
reg   [0:0] write_flag8_fu_220;
reg   [0:0] write_flag27_fu_224;
reg   [7:0] local_beta_buffer_V_25_fu_228;
reg   [7:0] local_beta_buffer_V_24_fu_232;
reg   [0:0] write_flag26_fu_236;
reg   [7:0] local_beta_buffer_V_23_fu_240;
reg   [0:0] write_flag11_fu_244;
reg   [0:0] write_flag25_fu_248;
reg   [7:0] local_beta_buffer_V_22_fu_252;
reg   [7:0] local_beta_buffer_V_21_fu_256;
reg   [0:0] write_flag24_fu_260;
reg   [7:0] local_beta_buffer_V_20_fu_264;
reg   [0:0] write_flag14_fu_268;
reg   [0:0] write_flag23_fu_272;
reg   [7:0] local_beta_buffer_V_19_fu_276;
reg   [7:0] local_beta_buffer_V_18_fu_280;
reg   [0:0] write_flag22_fu_284;
reg   [7:0] local_beta_buffer_V_17_fu_288;
reg   [0:0] write_flag17_fu_292;
reg   [0:0] write_flag21_fu_296;
reg   [7:0] local_beta_buffer_V_16_fu_300;
reg   [7:0] local_beta_buffer_V_15_fu_304;
reg   [0:0] write_flag20_fu_308;
reg   [7:0] local_beta_buffer_V_14_fu_312;
reg   [0:0] write_flag19_fu_316;
reg   [0:0] write_flag18_fu_320;
reg   [7:0] local_beta_buffer_V_13_fu_324;
reg   [7:0] local_beta_buffer_V_12_fu_328;
reg   [0:0] write_flag16_fu_332;
reg   [7:0] local_beta_buffer_V_11_fu_336;
reg   [0:0] write_flag15_fu_340;
reg   [0:0] write_flag13_fu_344;
reg   [7:0] local_beta_buffer_V_10_fu_348;
reg   [7:0] local_beta_buffer_V_9_fu_352;
reg   [0:0] write_flag12_fu_356;
reg   [7:0] local_beta_buffer_V_8_fu_360;
reg   [0:0] write_flag10_fu_364;
reg   [0:0] write_flag9_fu_368;
reg   [7:0] local_beta_buffer_V_7_fu_372;
reg   [7:0] local_beta_buffer_V_6_fu_376;
reg   [0:0] write_flag7_fu_380;
reg   [7:0] local_beta_buffer_V_5_fu_384;
reg   [0:0] write_flag6_fu_388;
reg   [0:0] write_flag5_fu_392;
reg   [7:0] local_beta_buffer_V_4_fu_396;
reg   [7:0] local_beta_buffer_V_3_fu_400;
reg   [0:0] write_flag3_fu_404;
reg   [7:0] local_beta_buffer_V_2_fu_408;
reg   [0:0] write_flag2_fu_412;
reg   [0:0] write_flag1_fu_416;
reg   [7:0] local_beta_buffer_V_1_fu_420;
wire   [7:0] local_beta_buffer_0_1_fu_1363_p3;
wire   [7:0] local_beta_buffer_1_1_fu_1370_p3;
wire   [7:0] local_beta_buffer_2_1_fu_1377_p3;
wire   [7:0] local_beta_buffer_3_1_fu_1384_p3;
wire   [7:0] local_beta_buffer_4_1_fu_1391_p3;
wire   [7:0] local_beta_buffer_5_1_fu_1398_p3;
wire   [7:0] local_beta_buffer_6_1_fu_1405_p3;
wire   [7:0] local_beta_buffer_7_1_fu_1412_p3;
wire   [7:0] local_beta_buffer_8_1_fu_1419_p3;
wire   [7:0] local_beta_buffer_9_1_fu_1426_p3;
wire   [7:0] local_beta_buffer_10_1_fu_1433_p3;
wire   [7:0] local_beta_buffer_11_1_fu_1440_p3;
wire   [7:0] local_beta_buffer_12_1_fu_1447_p3;
wire   [7:0] local_beta_buffer_13_1_fu_1454_p3;
wire   [7:0] local_beta_buffer_14_1_fu_1461_p3;
wire   [7:0] local_beta_buffer_15_1_fu_1468_p3;
wire   [7:0] local_beta_buffer_16_1_fu_1475_p3;
wire   [7:0] local_beta_buffer_17_1_fu_1482_p3;
wire   [7:0] local_beta_buffer_18_1_fu_1489_p3;
wire   [7:0] local_beta_buffer_19_1_fu_1496_p3;
wire   [7:0] local_beta_buffer_20_1_fu_1503_p3;
wire   [7:0] local_beta_buffer_21_1_fu_1510_p3;
wire   [7:0] local_beta_buffer_22_1_fu_1517_p3;
wire   [7:0] local_beta_buffer_23_1_fu_1524_p3;
wire   [7:0] local_beta_buffer_24_1_fu_1531_p3;
wire   [7:0] local_beta_buffer_25_1_fu_1538_p3;
wire   [7:0] local_beta_buffer_26_1_fu_1545_p3;
wire   [7:0] local_beta_buffer_27_1_fu_1552_p3;
wire   [7:0] local_beta_buffer_28_1_fu_1559_p3;
wire   [7:0] local_beta_buffer_29_1_fu_1566_p3;
wire   [7:0] local_beta_buffer_30_1_fu_1573_p3;
wire   [7:0] local_beta_buffer_31_1_fu_1580_p3;
reg   [2:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_condition_pp0_exit_iter0_state2) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_condition_pp0_exit_iter0_state2) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state2);
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (exitcond_fu_821_p2 == 1'd0))) begin
        offset_reg_635 <= offset_1_fu_841_p2;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        offset_reg_635 <= m;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (exitcond_fu_821_p2 == 1'd0))) begin
        tm_reg_644 <= tm_3_fu_826_p2;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        tm_reg_644 <= 6'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_204_reg_2379 == 5'd8) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        write_flag10_fu_364 <= 1'd1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        write_flag10_fu_364 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_204_reg_2379 == 5'd3) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        write_flag11_fu_244 <= 1'd1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        write_flag11_fu_244 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_204_reg_2379 == 5'd16) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        write_flag12_fu_356 <= 1'd1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        write_flag12_fu_356 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_204_reg_2379 == 5'd17) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        write_flag13_fu_344 <= 1'd1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        write_flag13_fu_344 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_204_reg_2379 == 5'd4) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        write_flag14_fu_268 <= 1'd1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        write_flag14_fu_268 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_204_reg_2379 == 5'd7) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        write_flag15_fu_340 <= 1'd1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        write_flag15_fu_340 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_204_reg_2379 == 5'd18) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        write_flag16_fu_332 <= 1'd1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        write_flag16_fu_332 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_204_reg_2379 == 5'd5) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        write_flag17_fu_292 <= 1'd1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        write_flag17_fu_292 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_204_reg_2379 == 5'd19) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        write_flag18_fu_320 <= 1'd1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        write_flag18_fu_320 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_204_reg_2379 == 5'd6) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        write_flag19_fu_316 <= 1'd1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        write_flag19_fu_316 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_204_reg_2379 == 5'd11) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        write_flag1_fu_416 <= 1'd1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        write_flag1_fu_416 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_204_reg_2379 == 5'd20) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        write_flag20_fu_308 <= 1'd1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        write_flag20_fu_308 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_204_reg_2379 == 5'd21) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        write_flag21_fu_296 <= 1'd1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        write_flag21_fu_296 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_204_reg_2379 == 5'd22) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        write_flag22_fu_284 <= 1'd1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        write_flag22_fu_284 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_204_reg_2379 == 5'd23) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        write_flag23_fu_272 <= 1'd1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        write_flag23_fu_272 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_204_reg_2379 == 5'd24) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        write_flag24_fu_260 <= 1'd1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        write_flag24_fu_260 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_204_reg_2379 == 5'd25) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        write_flag25_fu_248 <= 1'd1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        write_flag25_fu_248 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_204_reg_2379 == 5'd26) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        write_flag26_fu_236 <= 1'd1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        write_flag26_fu_236 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_204_reg_2379 == 5'd27) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        write_flag27_fu_224 <= 1'd1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        write_flag27_fu_224 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_204_reg_2379 == 5'd28) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        write_flag28_fu_212 <= 1'd1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        write_flag28_fu_212 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_204_reg_2379 == 5'd29) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        write_flag29_fu_200 <= 1'd1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        write_flag29_fu_200 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_204_reg_2379 == 5'd10) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        write_flag2_fu_412 <= 1'd1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        write_flag2_fu_412 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_204_reg_2379 == 5'd30) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        write_flag30_fu_188 <= 1'd1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        write_flag30_fu_188 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_204_reg_2379 == 5'd31) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        write_flag31_fu_176 <= 1'd1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        write_flag31_fu_176 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_204_reg_2379 == 5'd12) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        write_flag3_fu_404 <= 1'd1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        write_flag3_fu_404 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_204_reg_2379 == 5'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        write_flag4_fu_196 <= 1'd1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        write_flag4_fu_196 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_204_reg_2379 == 5'd13) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        write_flag5_fu_392 <= 1'd1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        write_flag5_fu_392 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_204_reg_2379 == 5'd9) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        write_flag6_fu_388 <= 1'd1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        write_flag6_fu_388 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_204_reg_2379 == 5'd14) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        write_flag7_fu_380 <= 1'd1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        write_flag7_fu_380 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_204_reg_2379 == 5'd2) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        write_flag8_fu_220 <= 1'd1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        write_flag8_fu_220 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_204_reg_2379 == 5'd15) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        write_flag9_fu_368 <= 1'd1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        write_flag9_fu_368 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_204_reg_2379 == 5'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        write_flag_fu_172 <= 1'd1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        write_flag_fu_172 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_204_reg_2379 == 5'd16) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_beta_buffer_V_10_fu_348 <= tmp_203_fu_847_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_204_reg_2379 == 5'd17) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_beta_buffer_V_11_fu_336 <= tmp_203_fu_847_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_204_reg_2379 == 5'd6) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_beta_buffer_V_12_fu_328 <= tmp_203_fu_847_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_204_reg_2379 == 5'd18) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_beta_buffer_V_13_fu_324 <= tmp_203_fu_847_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_204_reg_2379 == 5'd19) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_beta_buffer_V_14_fu_312 <= tmp_203_fu_847_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_204_reg_2379 == 5'd5) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_beta_buffer_V_15_fu_304 <= tmp_203_fu_847_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_204_reg_2379 == 5'd20) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_beta_buffer_V_16_fu_300 <= tmp_203_fu_847_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_204_reg_2379 == 5'd21) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_beta_buffer_V_17_fu_288 <= tmp_203_fu_847_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_204_reg_2379 == 5'd4) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_beta_buffer_V_18_fu_280 <= tmp_203_fu_847_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_204_reg_2379 == 5'd22) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_beta_buffer_V_19_fu_276 <= tmp_203_fu_847_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_204_reg_2379 == 5'd10) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_beta_buffer_V_1_fu_420 <= tmp_203_fu_847_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_204_reg_2379 == 5'd23) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_beta_buffer_V_20_fu_264 <= tmp_203_fu_847_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_204_reg_2379 == 5'd3) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_beta_buffer_V_21_fu_256 <= tmp_203_fu_847_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_204_reg_2379 == 5'd24) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_beta_buffer_V_22_fu_252 <= tmp_203_fu_847_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_204_reg_2379 == 5'd25) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_beta_buffer_V_23_fu_240 <= tmp_203_fu_847_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_204_reg_2379 == 5'd2) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_beta_buffer_V_24_fu_232 <= tmp_203_fu_847_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_204_reg_2379 == 5'd26) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_beta_buffer_V_25_fu_228 <= tmp_203_fu_847_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_204_reg_2379 == 5'd27) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_beta_buffer_V_26_fu_216 <= tmp_203_fu_847_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_204_reg_2379 == 5'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_beta_buffer_V_27_fu_208 <= tmp_203_fu_847_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_204_reg_2379 == 5'd28) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_beta_buffer_V_28_fu_204 <= tmp_203_fu_847_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_204_reg_2379 == 5'd29) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_beta_buffer_V_29_fu_192 <= tmp_203_fu_847_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_204_reg_2379 == 5'd11) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_beta_buffer_V_2_fu_408 <= tmp_203_fu_847_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_204_reg_2379 == 5'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_beta_buffer_V_30_fu_184 <= tmp_203_fu_847_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_204_reg_2379 == 5'd30) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_beta_buffer_V_31_fu_180 <= tmp_203_fu_847_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_204_reg_2379 == 5'd31) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_beta_buffer_V_32_fu_168 <= tmp_203_fu_847_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_204_reg_2379 == 5'd9) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_beta_buffer_V_3_fu_400 <= tmp_203_fu_847_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_204_reg_2379 == 5'd12) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_beta_buffer_V_4_fu_396 <= tmp_203_fu_847_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_204_reg_2379 == 5'd13) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_beta_buffer_V_5_fu_384 <= tmp_203_fu_847_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_204_reg_2379 == 5'd8) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_beta_buffer_V_6_fu_376 <= tmp_203_fu_847_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_204_reg_2379 == 5'd14) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_beta_buffer_V_7_fu_372 <= tmp_203_fu_847_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_204_reg_2379 == 5'd15) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_beta_buffer_V_8_fu_360 <= tmp_203_fu_847_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_204_reg_2379 == 5'd7) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_beta_buffer_V_9_fu_352 <= tmp_203_fu_847_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (exitcond_fu_821_p2 == 1'd0))) begin
        tmp_204_reg_2379 <= tmp_204_fu_837_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        tmp_reg_2360 <= tmp_fu_655_p2;
    end
end

always @ (*) begin
    if ((exitcond_fu_821_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state2 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        beta_buffer_ce0 = 1'b1;
    end else begin
        beta_buffer_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (exitcond_fu_821_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (exitcond_fu_821_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_return_0 = local_beta_buffer_0_1_fu_1363_p3;

assign ap_return_1 = local_beta_buffer_1_1_fu_1370_p3;

assign ap_return_10 = local_beta_buffer_10_1_fu_1433_p3;

assign ap_return_11 = local_beta_buffer_11_1_fu_1440_p3;

assign ap_return_12 = local_beta_buffer_12_1_fu_1447_p3;

assign ap_return_13 = local_beta_buffer_13_1_fu_1454_p3;

assign ap_return_14 = local_beta_buffer_14_1_fu_1461_p3;

assign ap_return_15 = local_beta_buffer_15_1_fu_1468_p3;

assign ap_return_16 = local_beta_buffer_16_1_fu_1475_p3;

assign ap_return_17 = local_beta_buffer_17_1_fu_1482_p3;

assign ap_return_18 = local_beta_buffer_18_1_fu_1489_p3;

assign ap_return_19 = local_beta_buffer_19_1_fu_1496_p3;

assign ap_return_2 = local_beta_buffer_2_1_fu_1377_p3;

assign ap_return_20 = local_beta_buffer_20_1_fu_1503_p3;

assign ap_return_21 = local_beta_buffer_21_1_fu_1510_p3;

assign ap_return_22 = local_beta_buffer_22_1_fu_1517_p3;

assign ap_return_23 = local_beta_buffer_23_1_fu_1524_p3;

assign ap_return_24 = local_beta_buffer_24_1_fu_1531_p3;

assign ap_return_25 = local_beta_buffer_25_1_fu_1538_p3;

assign ap_return_26 = local_beta_buffer_26_1_fu_1545_p3;

assign ap_return_27 = local_beta_buffer_27_1_fu_1552_p3;

assign ap_return_28 = local_beta_buffer_28_1_fu_1559_p3;

assign ap_return_29 = local_beta_buffer_29_1_fu_1566_p3;

assign ap_return_3 = local_beta_buffer_3_1_fu_1384_p3;

assign ap_return_30 = local_beta_buffer_30_1_fu_1573_p3;

assign ap_return_31 = local_beta_buffer_31_1_fu_1580_p3;

assign ap_return_4 = local_beta_buffer_4_1_fu_1391_p3;

assign ap_return_5 = local_beta_buffer_5_1_fu_1398_p3;

assign ap_return_6 = local_beta_buffer_6_1_fu_1405_p3;

assign ap_return_7 = local_beta_buffer_7_1_fu_1412_p3;

assign ap_return_8 = local_beta_buffer_8_1_fu_1419_p3;

assign ap_return_9 = local_beta_buffer_9_1_fu_1426_p3;

assign beta_buffer_address0 = tmp_s_fu_832_p1;

assign exitcond_fu_821_p2 = ((offset_reg_635 == tmp_reg_2360) ? 1'b1 : 1'b0);

assign local_beta_buffer_0_1_fu_1363_p3 = ((write_flag_fu_172[0:0] === 1'b1) ? local_beta_buffer_V_30_fu_184 : local_beta_buffer_0);

assign local_beta_buffer_10_1_fu_1433_p3 = ((write_flag2_fu_412[0:0] === 1'b1) ? local_beta_buffer_V_1_fu_420 : local_beta_buffer_10);

assign local_beta_buffer_11_1_fu_1440_p3 = ((write_flag1_fu_416[0:0] === 1'b1) ? local_beta_buffer_V_2_fu_408 : local_beta_buffer_11);

assign local_beta_buffer_12_1_fu_1447_p3 = ((write_flag3_fu_404[0:0] === 1'b1) ? local_beta_buffer_V_4_fu_396 : local_beta_buffer_12);

assign local_beta_buffer_13_1_fu_1454_p3 = ((write_flag5_fu_392[0:0] === 1'b1) ? local_beta_buffer_V_5_fu_384 : local_beta_buffer_13);

assign local_beta_buffer_14_1_fu_1461_p3 = ((write_flag7_fu_380[0:0] === 1'b1) ? local_beta_buffer_V_7_fu_372 : local_beta_buffer_14);

assign local_beta_buffer_15_1_fu_1468_p3 = ((write_flag9_fu_368[0:0] === 1'b1) ? local_beta_buffer_V_8_fu_360 : local_beta_buffer_15);

assign local_beta_buffer_16_1_fu_1475_p3 = ((write_flag12_fu_356[0:0] === 1'b1) ? local_beta_buffer_V_10_fu_348 : local_beta_buffer_16);

assign local_beta_buffer_17_1_fu_1482_p3 = ((write_flag13_fu_344[0:0] === 1'b1) ? local_beta_buffer_V_11_fu_336 : local_beta_buffer_17);

assign local_beta_buffer_18_1_fu_1489_p3 = ((write_flag16_fu_332[0:0] === 1'b1) ? local_beta_buffer_V_13_fu_324 : local_beta_buffer_18);

assign local_beta_buffer_19_1_fu_1496_p3 = ((write_flag18_fu_320[0:0] === 1'b1) ? local_beta_buffer_V_14_fu_312 : local_beta_buffer_19);

assign local_beta_buffer_1_1_fu_1370_p3 = ((write_flag4_fu_196[0:0] === 1'b1) ? local_beta_buffer_V_27_fu_208 : local_beta_buffer_1);

assign local_beta_buffer_20_1_fu_1503_p3 = ((write_flag20_fu_308[0:0] === 1'b1) ? local_beta_buffer_V_16_fu_300 : local_beta_buffer_20);

assign local_beta_buffer_21_1_fu_1510_p3 = ((write_flag21_fu_296[0:0] === 1'b1) ? local_beta_buffer_V_17_fu_288 : local_beta_buffer_21);

assign local_beta_buffer_22_1_fu_1517_p3 = ((write_flag22_fu_284[0:0] === 1'b1) ? local_beta_buffer_V_19_fu_276 : local_beta_buffer_22);

assign local_beta_buffer_23_1_fu_1524_p3 = ((write_flag23_fu_272[0:0] === 1'b1) ? local_beta_buffer_V_20_fu_264 : local_beta_buffer_23);

assign local_beta_buffer_24_1_fu_1531_p3 = ((write_flag24_fu_260[0:0] === 1'b1) ? local_beta_buffer_V_22_fu_252 : local_beta_buffer_24);

assign local_beta_buffer_25_1_fu_1538_p3 = ((write_flag25_fu_248[0:0] === 1'b1) ? local_beta_buffer_V_23_fu_240 : local_beta_buffer_25);

assign local_beta_buffer_26_1_fu_1545_p3 = ((write_flag26_fu_236[0:0] === 1'b1) ? local_beta_buffer_V_25_fu_228 : local_beta_buffer_26);

assign local_beta_buffer_27_1_fu_1552_p3 = ((write_flag27_fu_224[0:0] === 1'b1) ? local_beta_buffer_V_26_fu_216 : local_beta_buffer_27);

assign local_beta_buffer_28_1_fu_1559_p3 = ((write_flag28_fu_212[0:0] === 1'b1) ? local_beta_buffer_V_28_fu_204 : local_beta_buffer_28);

assign local_beta_buffer_29_1_fu_1566_p3 = ((write_flag29_fu_200[0:0] === 1'b1) ? local_beta_buffer_V_29_fu_192 : local_beta_buffer_29);

assign local_beta_buffer_2_1_fu_1377_p3 = ((write_flag8_fu_220[0:0] === 1'b1) ? local_beta_buffer_V_24_fu_232 : local_beta_buffer_2);

assign local_beta_buffer_30_1_fu_1573_p3 = ((write_flag30_fu_188[0:0] === 1'b1) ? local_beta_buffer_V_31_fu_180 : local_beta_buffer_30);

assign local_beta_buffer_31_1_fu_1580_p3 = ((write_flag31_fu_176[0:0] === 1'b1) ? local_beta_buffer_V_32_fu_168 : local_beta_buffer_31);

assign local_beta_buffer_3_1_fu_1384_p3 = ((write_flag11_fu_244[0:0] === 1'b1) ? local_beta_buffer_V_21_fu_256 : local_beta_buffer_3);

assign local_beta_buffer_4_1_fu_1391_p3 = ((write_flag14_fu_268[0:0] === 1'b1) ? local_beta_buffer_V_18_fu_280 : local_beta_buffer_4);

assign local_beta_buffer_5_1_fu_1398_p3 = ((write_flag17_fu_292[0:0] === 1'b1) ? local_beta_buffer_V_15_fu_304 : local_beta_buffer_5);

assign local_beta_buffer_6_1_fu_1405_p3 = ((write_flag19_fu_316[0:0] === 1'b1) ? local_beta_buffer_V_12_fu_328 : local_beta_buffer_6);

assign local_beta_buffer_7_1_fu_1412_p3 = ((write_flag15_fu_340[0:0] === 1'b1) ? local_beta_buffer_V_9_fu_352 : local_beta_buffer_7);

assign local_beta_buffer_8_1_fu_1419_p3 = ((write_flag10_fu_364[0:0] === 1'b1) ? local_beta_buffer_V_6_fu_376 : local_beta_buffer_8);

assign local_beta_buffer_9_1_fu_1426_p3 = ((write_flag6_fu_388[0:0] === 1'b1) ? local_beta_buffer_V_3_fu_400 : local_beta_buffer_9);

assign offset_1_fu_841_p2 = ($signed(offset_reg_635) + $signed(32'd1));

assign tm_3_fu_826_p2 = (tm_reg_644 + 6'd1);

assign tmp_203_fu_847_p1 = beta_buffer_q0[7:0];

assign tmp_204_fu_837_p1 = tm_reg_644[4:0];

assign tmp_fu_655_p2 = (m + 32'd32);

assign tmp_s_fu_832_p1 = offset_reg_635;

endmodule //copy_local_beta
